alias lol='cmatrix | lolcat'
alias sdn='shutdown now'
alias vimrc='vim ~/.vimrc'
alias balias='vim ~/.bash_aliases'
alias gh='cd ~/Documents/Websites/GitHub'
alias cdw='cd ~/Documents/Websites'
alias cda='cd ~/Documents/Apps'
alias ls='ls -lF --color=auto -a'
alias neolol='neofetch | lolcat'
alias lamp='sudo systemctl start mysqld && sudo systemctl start httpd'
alias lamp-stop='sudo systemctl stop mysqld && sudo systemctl stop httpd'
alias napoly='gh && cd NapolyFrontend && konsole && gh && cd NapolyAPI && konsole && redis-server && konsole'
alias cdlock='cd /usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components'
